### PR TITLE
Misc enhancements

### PR DESCRIPTION
**Pull request by phako**
Some enhancements I made while trying to add DKMS support

### CODE REVIEW

**Comment by mhier** [comment]
Please add documentation for the new env variables. Also I would suggest to print at start which overrides are in effect - in case of AUTOCLEAN with some sleep time to give the user a chance to intervene if this was by mistake. Setting this can be somewhat dangerous if you have uncommited manual changes like edits of the CONFIG or postinst files (in principle this was the reason why to ask so annoyingly in the first place...). env variables can easily be set and forgotten, so I see some potential for this to go wrong...

**Comment by phako** [comment]
image

**Comment by mhier** [comment]
> image

Will those messages ("Active overrides" + following two lines) also appear without the env vars being set? (I would suggest no, as extra messages have more visibility)

**Comment by mhier** [comment]
why is this not yet merged?

**Pull request merged**
